import fs from "node:fs";
import assert from "node:assert/strict";
const endpoint = fs.readFileSync("mmlab-contact-worker/src/automation-endpoint.js", "utf8");
const analysis = fs.readFileSync("mmlab-contact-worker/src/automation-analysis.js", "utf8");
const worker = fs.readFileSync("mmlab-contact-worker/src/worker-v2.js", "utf8");
const config = fs.readFileSync("contact-config.js", "utf8");
const ui = fs.readFileSync("assets/js/home-v9.js", "utf8");
const css = fs.readFileSync("assets/css/home-v9.css", "utf8");
assert.match(endpoint, /promptLoggedByWorker: false/);
assert.match(endpoint, /responseLoggedByWorker: false/);
assert.match(endpoint, /runtimeState/);
assert.match(analysis, /RETRYABLE_AUTOMATION_REASONS/);
assert.match(analysis, /attempts = 2/);
assert.match(worker, /fallbackReasonExposed: true/);
assert.match(worker, /transientRetryMaxAttempts: 2/);
assert.match(config, /MMLAB_AUTOMATION_HEALTH_ENDPOINT/);
assert.match(ui, /FALLBACK REASON/);
assert.match(ui, /humanReason/);
assert.match(ui, /loadRuntimeHealth/);
assert.match(css, /\.af9-runtime/);
assert.match(css, /\.af9-fallback-reason/);
console.log("V15B.1 runtime diagnostics contracts: OK");
